#!/usr/bin/env node

var rl = require('readline');
var program = require('commander');
var Util = require('../Common/Util');
var params = Util.loadYaml(__dirname + '/../config/params.yml').parameters;
var database = require('../Service/Database')(params);
var encryption = require('../Service/Encryption')(params);

program
    .option('-f, --force', 'Update database (be sure to execute only once)')
    .parse(process.argv);

var Message = database.model('Message');
Message
    .query()
    .then(function(messages) {
        var encryptedMessages = [];
        for (var i = 0; i < messages.length; i++) {

            console.log('Message text `' + messages[i].text + '`\n');

            messages[i].text = encryption.encrypt(messages[i].text);

            console.log('Encrypted to `' + messages[i].text + '`\n');

            encryptedMessages.push(messages[i]);
        }

        return messages;
    }).then(function(messages) {
        if (program.force) {
            var r = rl.createInterface({
                input: process.stdin,
                output: process.stdout
            });
            r.question('Are you sure that you want to persist the results? [y/n]' + '\n', function(answer) {
                r.close();
                if (answer.toLowerCase() === 'y') {
                    console.log('Persisting results to database...');

                    // TODO: Persist data

                    console.log('Done!');
                }

                process.exit(0);
            });

        } else {
            console.log('If you want to persist the results execute the same command with --force or -f');
            process.exit(0);
        }

    }

);