services:

    kernel:
        class    : /Service/Kernel
        autorun  : true

    database:
        class    : /Service/Database

    encryption:
        class    : /Service/Encryption

    socketAPI:
        class    : /Service/SocketAPI
        autorun  : true

    socketManager:
        class    : /Manager/SocketManager
        autorun  : true

    chatSocketManager:
        class    : /Manager/ChatSocketManager
        autorun  : true

    workersSocketManager:
        class    : /Manager/WorkersSocketManager

    pushNotificationsManager:
        class    : /Manager/PushNotificationsManager

    userManager:
        class    : /Manager/UserManager
