services:

    kernel:
        class    : /Service/Kernel
        autorun  : true

    database:
        class    : /Service/Database

    socketAPI:
        class    : /Service/SocketAPI
        autorun  : true

    socketManager:
        class    : /Manager/SocketManager
        autorun  : true

    chatSocketManager:
        class    : /Manager/ChatSocketManager
        autorun  : true

    workersSocketManager:
        class    : /Manager/WorkersSocketManager