services:

    kernel:
        class    : /Service/Kernel
        autorun  : true

    database:
        class    : /Service/Database

    socketManager:
        class    : /Manager/ChatManager
        autorun  : true
